### ISSUE TITLE
Fade bugs

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#8] opened 2019-12-16 22:38 UTC
Right clicking in sound strip header with a 0 frames fade and adding a fade in throws this error:
![image](https://user-images.githubusercontent.com/1322593/70947804-42ea0580-205a-11ea-8975-28705705870e.png)
Same thing with a 0 frames long Fade out(with no existing fade on the strip).
Maybe the default fade value(in the menu) should be one sec(according to the current settings?)

The fade menu could be added to the context menu and the Add menu?

**Comment by snuq** [comment] 2019-12-17 02:19
Looks like the script gets confused if the fade is already 0 and it tries to be set to 0, fixed.
I also set the default fade length to 10 frames, good idea there.

> The fade menu could be added to the context menu and the Add menu?

Not sure what you mean by this, it makes no sense to me for the fades to be in the add menu as that adds stuff to the sequencer.  I could maybe see it being in the strip menu, but the built-in functions are already in the add menu for some reason and i dont want two fades menus.

**Comment by tin2tin** [comment] 2019-12-17 13:51
I have not been using it enough, to be able to figure out if all functions and shortcuts are visible and accessible from the UI? 

Another fade thing I noticed is that pressing f 3 times for fade out and then left click for accepting it doesn't add a fade out at the correct duration.

This fade(and the volume draw) functions are moving the strip interactivity into the next level. Execelent work. 

I think the toolbar will soon be added(the next official release) with a very sparse set of functions, which means that functions can be added.

**Comment by snuq** [comment] 2019-12-17 19:06
> Another fade thing I noticed is that pressing f 3 times for fade out and then left click for accepting it doesn't add a fade out at the correct duration.

hmm, what do you mean not the correct duration? it seems to work fine on my setup

**Comment by tin2tin** [comment] 2019-12-17 20:12
Not able to reproduce now, and didn't save the previous session.

**Comment by snuq** [comment] 2019-12-17 21:12
alright, ill go ahead and close this for now, let me know if you can reproduce it later and i'll reopen it

**Closed by snuq** 2019-12-17 21:12 UTC
Labels: question
