### ISSUE TITLE
More testing and issues in Blender 4.0

### ISSUE THREAD

**Issue by MumuMundo** [snuq/VSEQF#27] opened 2023-12-03 15:34 UTC
I read the whole documentation and tried to test everything on the Blender 4.0 version, here's what I found:

* ripple moving strips moves locked strips too
* shift+m > add tag at cursor error
* zoom (to timeline, cursor) error + it adds a vseqf-temp-zoom strip
* file browser > import to clip editor not working
* features work even when disabled in the addon preferences
* auto parent audio to video : not working when new clip is dragged (it should be a global setting)
* when parent is duplicated, child is not
* Grab Multiple With Right-Click Drag > no option in settings menu?
* Making Meta Strip Additions (I don't understand this part)
* is the delete confirmation necessary? I prever the default VSE delete without confirmaion
* it's confusing when the addon and documentaion say Sequence instead of Strip
* selected to cursor seems to be the same as selected beginning to cursor
* error when 'follow cursor' button is enabled (and this feature is not mentioned in documentation)
* full timeline setup doesn't move the markers along with strips when ripple markers is enabled

**Comment by snuq** [comment] 2023-12-04 23:37
Thank you for all of this! I try to keep up with testing, but the random api changes in Blender means little things slip through a lot.
Ive been working through the list:

> ripple moving strips moves locked strips too

Looks like ripple cutting/delete didnt check for this (fixed now), but grabs already should have.  Does grab ripple locked strips for you in some situations?

> shift+m > add tag at cursor error

API change, fixed

> zoom (to timeline, cursor) error + it adds a vseqf-temp-zoom strip

API change, fixed

> file browser > import to clip editor not working

It does import it, you need to have a movie clip editor area open to have it actually selected tho

> features work even when disabled in the addon preferences

Oops... wow, thats been broken for a while and I didn't know about it! thanks for pointing that out

> auto parent audio to video : not working when new clip is dragged (it should be a global setting)

This is expected behavior unfortunately, I have not found a way to insert my own import code into drag and drop functions.

> when parent is duplicated, child is not

This is expected behavior, VSEQF does not override the duplicate modifier

> Grab Multiple With Right-Click Drag > no option in settings menu?

I dont understand what you mean here, can you provide more information?

> is the delete confirmation necessary? I prever the default VSE delete without confirmaion

What...?  Apparently this changed at some point, even tho its still default behavior elsewhere in blender... I can add an option to remove the confirmation (popup will be disabled by default to match Blender's behavior), but thats very weird.

> it's confusing when the addon and documentaion say Sequence instead of Strip

Blender's api itself is confused in this regard, some variables are strip and some are sequence.  I opted to go with Sequence since it made more sense to me at the time (sequence editor, sequence), but Blender seems to be gravitating more towards calling them Strips nowdays.  Ill think about changing this, but its not a high priority at the moment since my ocd would require me to refactor all the code variables as well!

> selected to cursor seems to be the same as selected beginning to cursor

Beginning to cursor always moves the sequence itself regardless of what edges are selected.  Its not a huge difference, but there is one.

> error when 'follow cursor' button is enabled (and this feature is not mentioned in documentation)

API change, fixed, added a quick note to documentation

> full timeline setup doesn't move the markers along with strips when ripple markers is enabled

Hmm, I dont think this should really be related to ripple, but it should indeed move the markers as it is a 'full timeline setup'.  Behavior has been changed to do this.

**Closed by snuq** 2023-12-04 23:37 UTC

**Comment by MumuMundo** [comment] 2023-12-05 06:45
Great! Thanks for all the fixes, I'll test again when I have time ^^
> I dont understand what you mean here, can you provide more information?
I'm refering to this part in the docs:
![image](https://github.com/snuq/VSEQF/assets/152472795/984247a2-e5ea-4deb-ae33-777375b4d077)
>  Delete confirmation : Apparently this changed at some point
it happens only when the addon is active.
